
#Name: Sita Rajagopal (1001677) and Elaine Cheong Yu Shan (1001721)


import hashlib

from itertools import product
import time
import random
import string

#part1: brute-force hash
#TIME TAKEN: 74.02

def bruteforce():
    alphabet='abcdefghijklmnopqrstuvwxyz1234567890'
    return [''.join(i) for i in product(alphabet, repeat = 5)]


fin_hash=open("hash5.txt",mode='r') # read the 15 hashes from hash5.txt
hashwords=fin_hash.read()
hashlines=hashwords.splitlines() 

starttime=time.time()
fin_hash.close()

hash_dictionary={}
for h in hashlines:
    hash_dictionary[h]='' #initalise the dictionary

permlist1=bruteforce()

for perms in permlist1:  #run through each element generated by bruteforce
    perms=perms.rstrip()
    hashpos=hashlib.md5(str.encode(perms)).hexdigest() 
    if hashpos in hash_dictionary:
        hash_dictionary[hashpos]=perms #add the hash to hash dictionary if there is matching element between perms and hashpos 
        print(perms,hashpos)
            
           
print(hash_dictionary)
print("Time used: ", round(time.time() - starttime, 2),"seconds")





#part 2 : adding salt 


fout=open('salted6.txt',mode='w')
fout_hash=open('hash6.txt',mode='w')
new_dict={}
for key in hash_dictionary:
    salt=random.choice(string.ascii_lowercase). # generate a random salt
    newkey=hash_dictionary[key]+salt.  #concentenate the password and the salt
    new_dict[newkey]=hashlib.md5(str.encode(newkey)).hexdigest() #hash the conentenated password and salt
    fout.write(hash_dictionary[key]+"-"+salt+": "+hashlib.md5(str.encode(newkey)).hexdigest()+"\n")
    fout_hash.write(hashlib.md5(str.encode(newkey)).hexdigest()+"\n")



    


    


    
   


